### ISSUE TITLE
Cannot delete S3 logging endpoint with / in its name

### ISSUE THREAD

**Issue by jwadolowski** [sethvargo/go-fastly#91] opened 2018-10-16 07:21 UTC
Hi Seth,

I've created an S3 logging endpoint named `prefix/xyz`. At some point I decided it is no longer needed, so wanted to delete it. According to [current implementation](https://github.com/sethvargo/go-fastly/blob/master/fastly/s3.go#L246) DELETE request will be send to `/service/SERVICE_ID/version/VERSION/logging/s3/ENDPOINT_NAME`, which translates to: `/service/SERVICE_ID/version/VERSION/logging/s3/prefix/xyz` in this particualr case. The request ends with 404.

To handle this case properly the name has to be url-encoded: `/service/SERVICE_ID/version/VERSION/logging/s3/prefix%2xyz`

The issue looks similar to #65.

**Comment by sethvargo** [comment] 2018-10-16 14:21
Yea this is a duplicate of #65. Unfortunately there's no easy way around this because sometimes fastly wants the `/` and sometimes it doesn't, and sometimes they change their API 😦

**Closed by sethvargo** 2018-10-16 14:21 UTC
